In [17]:
import quic_graph_lasso
import numpy as np

### Preliminary tests

In [15]:
X = np.random.randint(0,100, size=(5,5))
cov = np.cov(X)

In [19]:
np.max(np.abs(X)), X

(98,
 array([[70, 66, 74, 79, 84],
        [71, 56, 52,  4, 91],
        [45, 21, 70, 59, 63],
        [52, 66, 81, 47, 96],
        [75, 98, 56, 59, 77]]))

In [7]:
graph_lasso_model = quic_graph_lasso.QuicGraphicalLasso(init_method='precomputed')

In [10]:
b = graph_lasso_model.fit(cov, init_method='precomputed')

In [12]:
cov

array([[1725.7 , -281.9 , -671.95, -349.65, -176.85],
       [-281.9 ,  358.8 ,  160.9 ,  261.8 , -156.3 ],
       [-671.95,  160.9 , 1006.7 ,  397.65, -884.4 ],
       [-349.65,  261.8 ,  397.65,  735.3 , -121.3 ],
       [-176.85, -156.3 , -884.4 , -121.3 , 1419.8 ]])

In [11]:
b.__dict__

{'lam': 0.5,
 'mode': 'default',
 'tol': 1e-06,
 'max_iter': 1000,
 'Theta0': None,
 'Sigma0': None,
 'method': 'quic',
 'verbose': 0,
 'path': None,
 'score_metric': 'log_likelihood',
 'init_method': 'precomputed',
 'auto_scale': True,
 'opt_': 39.108811017020386,
 'cputime_': 9.6e-05,
 'iters_': 20,
 'duality_gap_': -6.938893903907228e-17,
 'sample_covariance_': array([[1725.7 , -281.9 , -671.95, -349.65, -176.85],
        [-281.9 ,  358.8 ,  160.9 ,  261.8 , -156.3 ],
        [-671.95,  160.9 , 1006.7 ,  397.65, -884.4 ],
        [-349.65,  261.8 ,  397.65,  735.3 , -121.3 ],
        [-176.85, -156.3 , -884.4 , -121.3 , 1419.8 ]]),
 'lam_scale_': 1725.7,
 'is_fitted_': True,
 'path_': None,
 'n_samples_': 5,
 'n_features_': 5,
 'precision_': array([[5.79474996e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 2.78706800e-03, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 9.93667

In [37]:
np.cov(X)

array([[ 696.3 , -479.95, -618.2 ,   72.35,  184.95],
       [-479.95,  875.3 ,  295.55,  301.6 ,  714.2 ],
       [-618.2 ,  295.55,  800.3 , -127.9 , -221.55],
       [  72.35,  301.6 , -127.9 ,  570.7 ,  415.4 ],
       [ 184.95,  714.2 , -221.55,  415.4 , 1522.3 ]])

In [36]:
b.sample_covariance_

array([[ 696.3 , -479.95, -618.2 ,   72.35,  184.95],
       [-479.95,  875.3 ,  295.55,  301.6 ,  714.2 ],
       [-618.2 ,  295.55,  800.3 , -127.9 , -221.55],
       [  72.35,  301.6 , -127.9 ,  570.7 ,  415.4 ],
       [ 184.95,  714.2 , -221.55,  415.4 , 1522.3 ]])

In [27]:
help(np.corrcoef)

Help on function corrcoef in module numpy:

corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
    Return Pearson product-moment correlation coefficients.
    
    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is
    
    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }
    
    The values of `R` are between -1 and 1, inclusive.
    
    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : bool, optional
        If `rowvar` is True (default), then each row represents a
        variab

In [24]:
help(graph_lasso_model)

Help on QuicGraphicalLasso in module quic_graph_lasso object:

class QuicGraphicalLasso(inverse_covariance.InverseCovarianceEstimator)
 |  QuicGraphicalLasso(lam=0.5, mode='default', tol=1e-06, max_iter=1000, Theta0=None, Sigma0=None, path=None, method='quic', verbose=0, score_metric='log_likelihood', init_method='corrcoef', auto_scale=True)
 |  
 |  Computes a sparse inverse covariance matrix estimation using quadratic
 |  approximation.
 |  
 |  The inverse covariance is estimated the sample covariance estimate
 |  $S$ as an input such that:
 |  
 |  $T_hat = max_{\Theta} logdet(Theta) - Trace(ThetaS) - \lambda|\Theta|_1 $
 |  
 |  Parameters
 |  -----------
 |  lam : scalar or 2D ndarray, shape (n_features, n_features) (default=0.5)
 |      Regularization parameters per element of the inverse covariance matrix.
 |  
 |      If a scalar lambda is used, a penalty matrix will be generated
 |      containing lambda for all values in both upper and lower triangles
 |      and zeros along

## Tests on the fake sc_atac data

In [1]:
import pandas as pd
import numpy as np
import anndata as ad
import scipy as sp
import matplotlib.pyplot as plt
import tqdm

# Create fake single-cell atac-seq data
counts = pd.DataFrame(np.random.randint(0, 100, size=(50, 200)),
                      index=['Cell_'+i for i in map(str, range(50))],
                      columns=['chr1_'+i+'_'+i for i in map(str, range(200))])

atac = ad.AnnData(counts)


def add_region_infos(AnnData,
                     sep=('_', '_'),
                     inplace=True):
    """
    Get region informations from the var_names of AnnData object.
    e.g. chr1_12345_12346 -> 'chromosome' : chr1, 'start' : 12345, 'end' : 12346
    These info will be added to var of AnnData object.
        adata.var['chromosome'] : chromosome
        adata.var['start'] : start position
        adata.var['end'] : end position

    Parameters
    ----------
    AnnData : AnnData object
        AnnData object with var_names as region names.
    sep : tuple, optional
        Separator of region names. The default is ('_', '_').
    
    Returns
    -------
    AnnData : AnnData object
        AnnData object with region informations in var.
    """
    # Check if user wants to modify AnnData inplace or return a copy
    if inplace:
        pass
    else:
        AnnData = AnnData.copy()
    regions_list = AnnData.var_names

    # Replace sep[1] with sep[0] to make it easier to split
    regions_list = regions_list.str.replace(sep[1], sep[0])

    # Split region names
    regions_list = regions_list.str.split(sep[0]).tolist()

    # Check if all regions have the same number of elements
    if set([len(i) for i in regions_list]) != set([3]):
        raise ValueError("""Not all regions have the same number of elements.
                         Check if sep is correct, it should be ({}, {}),
                         with only one occurence each in region names.""".format(sep[0], sep[1]))

    # Extract region informations from var_names
    region_infos = pd.DataFrame(regions_list,
                                index=AnnData.var_names,
                                columns=['chromosome', 'start', 'end'])

    # Convert start and end to int
    region_infos['start'] = region_infos['start'].astype(int)
    region_infos['end'] = region_infos['end'].astype(int)

    # Add region informations to var
    AnnData.var['chromosome'] = region_infos['chromosome']
    AnnData.var['start'] = region_infos['start']
    AnnData.var['end'] = region_infos['end']

    sort_regions(AnnData)
    # Return AnnData if inplace is False
    if inplace:
        pass
    else:
        return AnnData


def sort_regions(AnnData):
    """
    Sort regions by chromosome and start position.
    """
    AnnData.var.sort_values(['chromosome', 'start'], inplace=True)
    return AnnData


def get_distance_regions(AnnData, chromosomes=None):
    """
    Get distance between regions.
    """
    # Check if chromosomes is None
    if chromosomes is None:
        # Get chromosome list
        chromosomes = AnnData.var['chromosome'].unique().tolist()
    else:
        if not np.array([i in AnnData.var['chromosome'].unique() for i in chromosomes]).all():
            raise ValueError("""Chromosomes should be in AnnData.var['chromosome'].
                                Check if chromosomes is correct.""")

    # A dictionary to store distance between regions for each chromosome
    distances = {}

    # Get distance between regions for each chromosome
    for chromosome in chromosomes:
        chr_mask = AnnData.var['chromosome']==chromosome
        # Store start and end positions in two arrays
        m, n = np.meshgrid(AnnData.var['start'].values[chr_mask],
                           AnnData.var['end'].values[chr_mask])

        # Get distance between start of region m and end of region n
        distance = np.abs(m-n)
        # Substract length of the region to get distance between
        # end of region m and start of region n
        # a.k.a. distance between closest bases of two regions
        distance = (distance.T-(AnnData.var['end'].values[chr_mask]
                                - AnnData.var['start'].values[chr_mask])).T

        # Remove diagonal (distance between a region and itself)
        distance -= np.diag(distance)

        # Keep upper triangle of the distance matrix
        # (we don't want to calculate the same connection twice)
        distance = np.triu(distance, k=1)

        # Test if distance is negative
        if np.any(distance < 0):
            raise ValueError("""Distance between regions should be positive.
                            You might have overlapping regions.""")

        # Store distance in a dictionary
        distances[chromosome] = distance

    # Return distance
    return distances


def potential_connections(AnnData, threshold, chromosomes=None):
    """
    Get potential connections between regions based on distance.
    """
    # Check if chromosomes is None
    if chromosomes is None:
        # Get chromosome list
        chromosomes = AnnData.var['chromosome'].unique().tolist()
    else:
        if not np.array([i in AnnData.var['chromosome'].unique() for i in chromosomes]).all():
            raise ValueError("""Chromosomes should be in AnnData.var['chromosome'].
                                Check if chromosomes is correct.""")
    # Get distance between regions
    distances = get_distance_regions(AnnData, chromosomes=chromosomes)

    potential_connections = {}
    # Get potential connections
    for chromosome in chromosomes:
        print("Getting potential connections for chromosome {}...".format(chromosome))
        # Get potential connections for each chromosome
        distance = distances[chromosome]
        potential_chr_co = np.where((distance <= threshold)
                                         & (distance > 0))

        # Store potential connections in a dictionary
        potential_connections[chromosome] = potential_chr_co

    # Return potential connections
    return potential_connections


def corrcoef_connections(AnnData, potential_connections, as_sparse=True):
    """
    Get correlation coefficient between regions.
    """
    # Transform potential_connections into a sparse matrix
    potential_connections = global_sparse(AnnData, potential_connections)

    # Get correlation coefficient between regions
    corr_coefs = [np.cov(AnnData.X[:, potential_connections.row[i]],
                              AnnData.X[:, potential_connections.col[i]])[0, 1]
                  for i in tqdm.tqdm(range(len(potential_connections.row)))]

    # Convert to sparse matrix if as_sparse is True
    if as_sparse:
        corr_coefs = sp.sparse.coo_matrix((corr_coefs,
                                           (potential_connections.row,
                                            potential_connections.col)),
                                          shape=(AnnData.shape[1],
                                                 AnnData.shape[1]))
    else:
        corr_coefs = np.array(corr_coefs)
    
    # Return correlation coefficients
    return corr_coefs




    # A dictionary storing the informations to create a sparse matrix of potential connections
    corr_coefs = {}
    corr_coefs['values'] = np.array([])
    corr_coefs['idx'] = np.array([])
    corr_coefs['idy'] = np.array([])

    # Get correlation coefficient between regions for each chromosome
    for chromosome in potential_connections.keys():
        chr_mask = AnnData.var['chromosome']==chromosome
        print("Getting correlation coefficient for chromosome {}...".format(chromosome))

        corr_coefs_chr = [np.corrcoef(AnnData.X[:,chr_mask][:, potential_connections[chromosome][0][i]],
                                      AnnData.X[:,chr_mask][:, potential_connections[chromosome][1][i]])[0, 1]
                          for i in range(len(potential_connections[chromosome][0]))]

        # Store correlation coefficient in a dictionary
        corr_coefs[chromosome] = corr_coefs_chr
    return corr_coefs


def global_sparse(AnnData, chr_idx, values = 1):
    """
    Create a sparse matrix from a dictionary of np.where output on 'regions*regions' matrices.of different chromosomes.
    using global indices of an AnnData object.

    e.g.:
    AnnData.var_names = ['chr1_12345_12346', 'chr1_12347_12348', 'chr2_12345_12346', 'chr2_12347_12348']
    And we know values for  (chr1_12345_12346, chr1_12347_12348),
                            (chr1_12347_12348, chr1_12345_12346),
                            (chr2_12345_12346, chr2_12345_12346),
                            (chr2_12347_12348, chr2_12347_12348).
    
    We can create a sparse matrix with 'chr_dic' defined as:
    chr_dic = {'chr1' : np.array([[1, 0], [0, 1]]),
               'chr2' : np.array([[0, 0], [1, 1]])}

    sparse_mtx = global_sparse(AnnData, chr_dic)
    sparse_mtx
    'OUTPUT' :               chr_1_12345_12346  chr_1_12347_12348  chr_2_12345_12346  chr_2_12347_12348
    chr_1_12345_12346                 *                  1                  *                  *
    chr_1_12347_12348                 1                  *                  *                  *
    chr_2_12345_12346                 *                  *                  1                  *
    chr_2_12347_12348                 *                  *                  *                  1

    Parameters
    ----------
    AnnData : AnnData object
        AnnData object with var_names as region names.
    chr_dic : dictionary
        Dictionary of matrices (regions*regions) of different chromosomes.
    """

    data = {}
    data['values'] = np.array([])
    data['idx'] = np.array([])
    data['idy'] = np.array([])

    for chromosome in chr_idx.keys():
        chr_mask = AnnData.var['chromosome'] == chromosome
        # Get region names (needed to get global indices)
        indices_names = AnnData.var_names[chr_mask][chr_idx[chromosome][0]]
        columns_names = AnnData.var_names[chr_mask][chr_idx[chromosome][1]]
        map_indices = {AnnData.var_names[i]: i
                       for i in range(len(AnnData.var_names))}

        # Add global indices of potential connections
        data['idx'] = np.concatenate([data['idx'],
                                      indices_names.map(map_indices).values])
        data['idy'] = np.concatenate([data['idy'],
                                      columns_names.map(map_indices).values])
        # Add values of potential connections
        if type(values) == int:
            val = np.repeat(values, len(chr_idx[chromosome][0]))
        elif type(values) == dict:
            val = values[chromosome]
        else:
            raise ValueError("""values should be an int,
                             or a dict (of numpy arrays).""")
        data['values'] = np.concatenate([data['values'],
                                         val])
    # Create sparse matrix
    sparse_data = sp.sparse.coo_matrix((data['values'],
                                        (data['idx'],
                                         data['idy'])),
                                       shape=(AnnData.shape[1],
                                              AnnData.shape[1]))

    return sparse_data


In [2]:
import numpy as np
import pandas as pd
import anndata as ad
import scipy as sp

import quic_graph_lasso

## Create dataset

In [3]:
# Create fake single-cell atac-seq data
nb_cells = 300
nb_chr = 10
nb_regions_per_chr = 200
between_reg = 1000
size_reg = 50

counts = []
for chr in range(nb_chr):
    counts.append(pd.DataFrame(np.random.randint(0,100, size=(nb_cells, nb_regions_per_chr)),
                        index=['Cell_'+j for j in map(str, range(nb_cells))],
                        columns=['chr'+str(chr)+'_'+str(i)+'_'+str(i+size_reg) for i in range(1, nb_regions_per_chr*between_reg+1, between_reg)]))
atac = ad.AnnData(pd.concat(counts, axis=1))

In [156]:
distance_threshold = 50000

### 1/5 Add region position in AnnData.obs

In [157]:
add_region_infos(atac)

### 2/5 Get potential pairs of connected regions (per chromosome)

In [159]:
potential_connections_atac = potential_connections(atac, threshold=distance_threshold)

Getting potential connections for chromosome chr0...
Getting potential connections for chromosome chr1...
Getting potential connections for chromosome chr2...
Getting potential connections for chromosome chr3...
Getting potential connections for chromosome chr4...
Getting potential connections for chromosome chr5...
Getting potential connections for chromosome chr6...
Getting potential connections for chromosome chr7...
Getting potential connections for chromosome chr8...
Getting potential connections for chromosome chr9...


### 3/5 Calculate correlations (cov in fact)

In [221]:
sample_cov = corrcoef_connections(atac, potential_connections_atac, as_sparse=True)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 87250/87250 [00:01<00:00, 45080.24it/s]


### 4/5 Calculate penalty associated with distance for each pair of regions

_Calculate the euclidean distance between all pair of region (per chromosome)_

In [225]:
distance = get_distance_regions(atac)

In [237]:
sp.sparse.csr_matrix(sample_cov)[[4,6],:5]

<2x5 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [226]:
extract_sliding_submatrix

{'chr0': array([[     0,    900,   1900, ..., 196900, 197900, 198900],
        [     0,      0,    900, ..., 195900, 196900, 197900],
        [     0,      0,      0, ..., 194900, 195900, 196900],
        ...,
        [     0,      0,      0, ...,      0,    900,   1900],
        [     0,      0,      0, ...,      0,      0,    900],
        [     0,      0,      0, ...,      0,      0,      0]]),
 'chr1': array([[     0,    900,   1900, ..., 196900, 197900, 198900],
        [     0,      0,    900, ..., 195900, 196900, 197900],
        [     0,      0,      0, ..., 194900, 195900, 196900],
        ...,
        [     0,      0,      0, ...,      0,    900,   1900],
        [     0,      0,      0, ...,      0,      0,    900],
        [     0,      0,      0, ...,      0,      0,      0]]),
 'chr2': array([[     0,    900,   1900, ..., 196900, 197900, 198900],
        [     0,      0,    900, ..., 195900, 196900, 197900],
        [     0,      0,      0, ..., 194900, 195900, 196900],
 

In [222]:
k = 300
graph_lasso_model = quic_graph_lasso.QuicGraphicalLasso(init_method='precomputed', lam=np.random.random(size = (k,k)))

In [223]:
sample_cov = sample_cov.toarray() + sample_cov.T.toarray()
#sample_cov = sample_cov - (np.diag(sample_cov) - 1e-4) * np.eye(sample_cov.shape[0])
sample_cov += 1e-4 * np.eye(sample_cov.shape[0])
results = graph_lasso_model.fit(sample_cov[:k,:k], tol=1e-6)

In [224]:
(results.covariance_ - np.diag(results.covariance_)*np.eye(len(results.covariance_))).sum()

-648.7245551044573

In [162]:
results = graph_lasso_model.fit(atac.X[:200,:30].T, tol=1e-2)

In [163]:
(results.covariance_ - np.diag(results.covariance_)*np.eye(len(results.covariance_))).sum()

2.1513101824912457

In [164]:
graph_lasso_model = quic_graph_lasso.QuicGraphicalLasso(init_method='precomputed', lam=0.5)

In [177]:
sample_cov

<2000x2000 sparse matrix of type '<class 'numpy.float64'>'
	with 87250 stored elements in COOrdinate format>

In [ ]:
(results.covariance_ - np.diag(results.covariance_)*np.eye(len(results.covariance_))).sum()
#results.covariance_.shape

In [138]:
cov = np.corrcoef(atac.X[:200,:30])
cov = cov - (np.eye(len(cov))/np.diag(cov) - 1)

In [139]:
np.max(cov)

1.7231138584847492

In [13]:
from scipy.sparse import issparse

In [14]:
issparse(sample_cov)

True

In [21]:
np.max(np.abs(sample_cov.data))

249.13752508361202

In [297]:
sparse = sp.sparse.coo_matrix(sample_cov)

In [294]:
sparse = sp.sparse.csr_matrix(sparse)

In [296]:
sparse[:5,:5]

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [298]:
blop = np.where(sparse.data>0)

In [299]:
blop2 = np.where(sparse.data>0)

In [310]:
pos_mask1 = np.where(sparse.data>0)
pos_idx1 = sparse.row[pos_mask1]
pos_idy1 = sparse.col[pos_mask1]

In [315]:
s1 = sparse
s2 = sparse

In [357]:
s1.data

array([ 1.00000000e-04,  2.86204013e+00, -7.87468896e+01, ...,
        2.99430881e+01,  2.67039576e+01,  1.00000000e-04])

In [368]:
pos_coord1 = {(x,y) for x,y,d in zip(s1.row, s1.col, s1.data) if d>=0}
pos_coord2 = {(x,y) for x,y,d in zip(s2.row, s2.col, s2.data) if d>=0}
pos_coord = pd.DataFrame(pos_coord1.intersection(pos_coord2), columns = ['row', 'col'])

neg_coord1 = {(x,y) for x,y,d in zip(s1.row, s1.col, s1.data) if d<=0}
neg_coord2 = {(x,y) for x,y,d in zip(s2.row, s2.col, s2.data) if d<=0}
neg_coord = pd.DataFrame(neg_coord1.intersection(neg_coord2), columns = ['row', 'col'])

In [370]:
pd.concat(neg_coord , pos_coord)

TypeError: concat() takes 1 positional argument but 2 were given

In [333]:
common = {}
common['row'] = np.array(bb)[:,0]
common['col'] = np.array(bb)[:,0]

array([1426, 1025, 1467, ..., 1625,  229,  934], dtype=int32)

In [352]:
sp.sparse.csr_matrix(s1)[(s1 + s2) > 0]

matrix([[1.00000000e-04, 2.86204013e+00, 6.95003344e+00, ...,
         2.99430881e+01, 2.67039576e+01, 1.00000000e-04]])

In [348]:
type(s1.multiply(s2))

scipy.sparse._csr.csr_matrix

In [317]:
import tqdm

[True if c1 in coord2 else False for c1 in tqdm.tqdm(coord1)]
[True if c2 in coord1 else False for c2 in tqdm.tqdm(coord2)]


KeyboardInterrupt: 

In [287]:
sparse.__dict__

{'_shape': (2000, 2000),
 'maxprint': 50,
 'data': array([ 1.00000000e-04,  2.86204013e+00, -7.87468896e+01, ...,
         2.99430881e+01,  2.67039576e+01,  1.00000000e-04]),
 'indices': array([   0,    1,    2, ..., 1997, 1998, 1999], dtype=int32),
 'indptr': array([     0,     51,    103, ..., 176397, 176449, 176500], dtype=int32)}

In [283]:
sparse[:4,:5]

TypeError: 'coo_matrix' object is not subscriptable

In [262]:
#%%timeit
np.where(np.abs(sp.sparse.csr_matrix(sample_cov)) - np.abs(sp.sparse.csr_matrix(sample_cov) - sp.sparse.csr_matrix(sample_cov)).todense())

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

In [260]:
np.array(d)

(array([   0,    0,    0, ..., 1999, 1999, 1999]),
 array([   0,    1,    2, ..., 1997, 1998, 1999]))